### ISSUE TITLE
Allow CA only verification of Elasticsearch backend certs

### ISSUE THREAD

**Issue by gusnuf** [cristifalcas/puppet-kibana#3]
Currently if `elasticsearch_ssl_enable` is true, default values are passed to `elasticsearch.ssl.key` and `elasticsearch.ssl.cert`.  Please make these unset by default, similar to the behavior of `elasticsearch.username` and `elasticsearch.password`.  Kibana allows you verify SSL with only the CA set, it just makes sure the certificates being used by ElasticSearch are signed by that CA.

**Comment by cristifalcas** [comment]
This is fixed in latest release now.

Also, it seems I forgot to tag the v5 release in github. The major version has changed to 5.x
